### ISSUE TITLE
reload of safari shows data instead of rendered HTML

### ISSUE THREAD

**Issue by chancesmith** [noamr/h0#6]
On the movie example, if I close safari app and come back I see the data instead of the styled app.

Just me?

https://user-images.githubusercontent.com/4466585/204145377-fada19e4-4a25-4acd-a21f-af846e2bfef3.MOV

**Comment by noamr** [comment]
Might be an issue with the service worker (which I've since removed...)

**Comment by noamr** [comment]
I think the bug doesn't exist anymore, but to make it disappear you need to clear the site data once (https://discussions.apple.com/thread/251163101)

**Comment by chancesmith** [comment]
Yep, that worked for me 😎
